import { Capture, Patient, Session, Eye, SessionType } from '../backend';
import { getQualityScore } from '../gallery/localPersistence';

function formatSessionType(type: SessionType): string {
  switch (type) {
    case SessionType.routine:
      return 'Routine';
    case SessionType.followUp:
      return 'Follow-up';
    case SessionType.emergency:
      return 'Emergency';
    default:
      return 'Unknown';
  }
}

function formatEye(eye: Eye): string {
  return eye === Eye.left ? 'Left' : 'Right';
}

// Browser-native PDF-like report using HTML canvas and download
export async function generatePDFReport(
  patient: Patient,
  session: Session,
  captures: Capture[],
  selectedIndices?: number[]
): Promise<void> {
  // Since we can't use jsPDF (package.json is read-only), we'll create an HTML report
  // that can be printed to PDF by the browser
  
  const capturesToInclude = selectedIndices
    ? captures.filter((_, i) => selectedIndices.includes(i))
    : captures.slice(0, 5);

  // Create HTML report
  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>EarScope Pro - Medical Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #333;
    }
    h1 {
      text-align: center;
      color: #2563eb;
      border-bottom: 2px solid #2563eb;
      padding-bottom: 10px;
    }
    h2 {
      color: #2563eb;
      margin-top: 30px;
      border-bottom: 1px solid #ddd;
      padding-bottom: 5px;
    }
    .info-section {
      margin: 20px 0;
    }
    .info-row {
      margin: 8px 0;
      display: flex;
    }
    .info-label {
      font-weight: bold;
      width: 150px;
    }
    .capture-section {
      margin: 30px 0;
      page-break-inside: avoid;
    }
    .capture-image {
      max-width: 100%;
      border: 1px solid #ddd;
      border-radius: 4px;
      margin: 10px 0;
    }
    .capture-info {
      font-size: 14px;
      color: #666;
      margin: 5px 0;
    }
    .footer {
      margin-top: 50px;
      text-align: center;
      font-size: 12px;
      color: #999;
      border-top: 1px solid #ddd;
      padding-top: 10px;
    }
    @media print {
      body {
        margin: 0;
        padding: 15px;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <h1>EarScope Pro - Medical Report</h1>
  
  <h2>Patient Information</h2>
  <div class="info-section">
    <div class="info-row">
      <span class="info-label">Name:</span>
      <span>${patient.name}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Patient ID:</span>
      <span>${patient.id}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Age:</span>
      <span>${patient.age}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Doctor:</span>
      <span>${patient.doctor}</span>
    </div>
  </div>
  
  <h2>Session Information</h2>
  <div class="info-section">
    <div class="info-row">
      <span class="info-label">Session Type:</span>
      <span>${formatSessionType(session.sessionType)}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Ear:</span>
      <span>${formatEye(session.eye)}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Date:</span>
      <span>${new Date(Number(session.timestamp) / 1000000).toLocaleString()}</span>
    </div>
  </div>
  
  <h2>Captured Images</h2>
`;

  // Add images
  for (let i = 0; i < capturesToInclude.length; i++) {
    const capture = capturesToInclude[i];
    try {
      const imageUrl = capture.image.getDirectURL();
      const timestamp = new Date(Number(capture.timestamp) / 1000000).toLocaleString();
      const qualityScore = getQualityScore(capture.id);
      
      html += `
  <div class="capture-section">
    <h3>Capture ${i + 1}</h3>
    <img src="${imageUrl}" alt="Capture ${i + 1}" class="capture-image" />
    <div class="capture-info">Timestamp: ${timestamp}</div>
    ${qualityScore !== null ? `<div class="capture-info">Quality Score: ${qualityScore}/10</div>` : ''}
  </div>
`;
    } catch (error) {
      console.error(`Failed to add image ${i + 1}:`, error);
      html += `
  <div class="capture-section">
    <h3>Capture ${i + 1}</h3>
    <p style="color: #999;">[Image could not be loaded]</p>
  </div>
`;
    }
  }

  html += `
  <div class="footer">
    Generated by EarScope Pro - ${new Date().toLocaleDateString()}
  </div>
  
  <div class="no-print" style="margin-top: 30px; text-align: center;">
    <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; background: #2563eb; color: white; border: none; border-radius: 4px; cursor: pointer;">
      Print / Save as PDF
    </button>
    <button onclick="window.close()" style="padding: 10px 20px; font-size: 16px; background: #6b7280; color: white; border: none; border-radius: 4px; cursor: pointer; margin-left: 10px;">
      Close
    </button>
  </div>
</body>
</html>
`;

  // Open in new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  } else {
    // Fallback: download as HTML
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `earscope_report_${patient.name}_${session.id}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
