/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Capture {
  'id' : string,
  'thumbnail' : ExternalBlob,
  'qualityScore' : [] | [bigint],
  'timestamp' : Time,
  'sessionId' : string,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export type Eye = { 'left' : null } |
  { 'right' : null };
export interface Patient {
  'id' : string,
  'age' : bigint,
  'doctor' : string,
  'name' : string,
}
export interface Session {
  'id' : string,
  'eye' : Eye,
  'sessionType' : SessionType,
  'patientId' : string,
  'timestamp' : Time,
}
export type SessionType = { 'emergency' : null } |
  { 'followUp' : null } |
  { 'routine' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCapture' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob],
    undefined
  >,
  'addPatient' : ActorMethod<[string, string, bigint, string], undefined>,
  'addSession' : ActorMethod<[string, string, SessionType, Eye], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCaptures' : ActorMethod<[], Array<Capture>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapture' : ActorMethod<[string], [] | [Capture]>,
  'getPatient' : ActorMethod<[string], [] | [Patient]>,
  'getSession' : ActorMethod<[string], [] | [Session]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];