/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SessionType = IDL.Variant({
  'emergency' : IDL.Null,
  'followUp' : IDL.Null,
  'routine' : IDL.Null,
});
export const Eye = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Capture = IDL.Record({
  'id' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'qualityScore' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'sessionId' : IDL.Text,
  'image' : ExternalBlob,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'doctor' : IDL.Text,
  'name' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Text,
  'eye' : Eye,
  'sessionType' : SessionType,
  'patientId' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCapture' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
      [],
      [],
    ),
  'addPatient' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addSession' : IDL.Func([IDL.Text, IDL.Text, SessionType, Eye], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCaptures' : IDL.Func([], [IDL.Vec(Capture)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapture' : IDL.Func([IDL.Text], [IDL.Opt(Capture)], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SessionType = IDL.Variant({
    'emergency' : IDL.Null,
    'followUp' : IDL.Null,
    'routine' : IDL.Null,
  });
  const Eye = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Capture = IDL.Record({
    'id' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'qualityScore' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'sessionId' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'doctor' : IDL.Text,
    'name' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : IDL.Text,
    'eye' : Eye,
    'sessionType' : SessionType,
    'patientId' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCapture' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
        [],
        [],
      ),
    'addPatient' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addSession' : IDL.Func([IDL.Text, IDL.Text, SessionType, Eye], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCaptures' : IDL.Func([], [IDL.Vec(Capture)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapture' : IDL.Func([IDL.Text], [IDL.Opt(Capture)], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };